# Generated by Django 5.1.1 on 2024-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panne',
            name='infrastructure',
        ),
        migrations.RenameField(
            model_name='panne',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='panne',
            name='titre',
            field=models.CharField(default='Titre par défaut', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
    ]
